[package]
name = "zksync_os_snark_prover"
edition.workspace = true
#rust-version.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zksync_sequencer_proof_client.workspace = true

zksync_airbender_cli.workspace = true
zksync_airbender_execution_utils.workspace = true
zkos_wrapper.workspace = true

#zksync_task_management = { path = "../core/lib/task_management" }
#sequencer_proof_client = { path = "../sequencer_proof_client" }

tokio.workspace = true
serde_json.workspace = true

serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true

[features]
default = ["zksync_airbender_cli/gpu", "zkos_wrapper/gpu"]